In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('call_activity.csv')
df

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,AZ,192,415,No,Yes,36,156.2,77.0,26.55,215.5,126.0,18.32,279.1,83.0,12.56,9.9,6,2.67,2.0,False
3329,WV,68,415,No,No,0,231.1,57.0,39.29,153.4,55.0,13.04,191.3,123.0,8.61,9.6,4,2.59,3.0,False
3330,RI,28,510,No,No,0,180.8,109.0,30.74,288.8,58.0,24.55,191.9,91.0,8.64,14.1,6,3.81,2.0,False
3331,CT,184,510,Yes,No,0,213.8,105.0,36.35,159.6,84.0,13.57,139.2,137.0,6.26,5.0,10,1.35,2.0,False
3332,TN,74,415,No,Yes,25,234.4,113.0,39.85,265.9,82.0,22.60,241.4,77.0,10.86,13.7,4,3.70,0.0,False

In [8]:
df.head(20)

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False
5,AL,118,510,Yes,No,0,223.4,98.0,37.98,220.6,101.0,18.75,203.9,118.0,9.18,6.3,6,1.70,0.0,False
6,MA,121,510,No,Yes,24,218.2,88.0,37.09,348.5,108.0,29.62,212.6,118.0,9.57,7.5,7,2.03,3.0,NaN
7,MO,147,415,Yes,No,0,157.0,79.0,26.69,103.1,94.0,8.76,211.8,96.0,9.53,7.1,6,1.92,0.0,False
8,LA,117,408,No,No,0,184.5,97.0,31.37,351.6,80.0,29.89,215.8,90.0,9.71,8.7,4,2.35,1.0,False
9,WV,141,415,Yes,Yes,37,258.6,84.0,43.96,222.0,111.0,18.87,326.4,97.0,14.69,11.2,5,3.02,0.0,False
10,IN,65,415,No,No,0,129.1,137.0,21.95,228.5,83.0,19.42,208.8,111.0,9.40,12.7,6,3.43,4.0,True
11,RI,74,415,No,No,0,187.7,127.0,31.91,163.4,148.0,13.89,196.0,94.0,8.82,9.1,5,2.46,0.0,False
12,IA,168,408,No,No,0,NaN,NaN,NaN,104.9,71.0,8.92,141.1,128.0,6.35,11.2,2,3.02,1.0,False
13,MT,95,510,No,No,0,NaN,NaN,NaN,247.6,75.0,21.05,192.3,115.0,8.65,12.3,5,3.32,3.0,False
14,IA,62,415,No,No,0,NaN,NaN,NaN,307.2,76.0,26.11,203.0,99.0,9.14,13.1,6,3.54,4.0,False
15,NY,161,415,No,No,0,NaN,NaN,NaN,317.8,97.0,27.01,160.6,128.0,7.23,5.4,9,1.46,4.0,True
16,ID,85,408,No,Yes,27,NaN,NaN,NaN,280.9,90.0,23.88,89.3,NaN,4.02,13.8,4,3.73,1.0,False
17,VT,93,510,No,No,0,NaN,NaN,NaN,218.2,111.0,18.55,129.6,121.0,5.83,8.1,3,2.19,3.0,False
18,VA,76,510,No,Yes,33,NaN,NaN,NaN,212.8,65.0,18.09,165.7,108.0,7.46,10.0,5,2.70,1.0,False
19,TX,73,415,No,No,0,NaN,NaN,NaN,NaN,88.0,13.56,192.8,74.0,8.68,13.0,2,3.51,1.0,False

In [10]:
type(df)

pandas.core.frame.DataFrame

In [12]:
df['State']

0       KS
1       OH
2       NJ
3       OH
4       OK
        ..
3328    AZ
3329    WV
3330    RI
3331    CT
3332    TN
Name: State, Length: 3333, dtype: object

In [9]:
df.tail(30)

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
3303,WI,114,415,No,Yes,26,137.1,88.0,23.31,155.7,125.0,13.23,247.6,94.0,11.14,11.5,7,3.11,2.0,False
3304,IL,71,510,Yes,No,0,186.1,114.0,31.64,198.6,140.0,16.88,206.5,80.0,9.29,13.8,5,3.73,4.0,True
3305,IN,58,415,No,Yes,22,224.1,127.0,38.10,238.8,85.0,20.30,174.2,86.0,7.84,11.5,7,3.11,2.0,False
3306,AL,106,408,No,Yes,29,83.6,131.0,14.21,203.9,131.0,17.33,229.5,73.0,10.33,8.1,3,2.19,1.0,False
3307,OK,172,408,No,No,0,203.9,109.0,34.66,234.0,123.0,19.89,160.7,65.0,7.23,17.8,4,4.81,4.0,False
3308,IA,45,415,No,No,0,211.3,87.0,35.92,165.7,97.0,14.08,265.9,72.0,11.97,13.3,6,3.59,1.0,False
3309,VT,100,408,Yes,No,0,219.4,112.0,37.30,225.7,102.0,19.18,255.3,95.0,11.49,12.0,4,3.24,4.0,False
3310,NY,94,415,No,No,0,190.4,91.0,32.37,92.0,107.0,7.82,224.8,108.0,10.12,13.6,17,3.67,2.0,False
3311,LA,128,415,No,No,0,147.7,94.0,25.11,283.3,83.0,24.08,188.3,124.0,8.47,6.9,5,1.86,2.0,False
3312,SC,181,408,No,No,0,229.9,130.0,39.08,144.4,93.0,12.27,262.4,110.0,11.81,14.2,4,3.83,2.0,False
3313,ID,127,408,No,No,0,102.8,128.0,17.48,143.7,95.0,12.21,191.4,97.0,8.61,10.0,5,2.70,1.0,False
3314,MO,89,415,No,No,0,178.7,81.0,30.38,233.7,74.0,19.86,131.9,120.0,5.94,9.1,4,2.46,1.0,False
3315,ME,149,415,No,Yes,18,148.5,106.0,25.25,114.5,106.0,9.73,178.3,98.0,8.02,6.5,4,1.76,0.0,False
3316,MS,103,510,No,Yes,29,164.1,111.0,27.90,219.1,96.0,18.62,220.3,108.0,9.91,12.3,9,3.32,0.0,False
3317,SD,163,415,Yes,No,0,197.2,90.0,33.52,188.5,113.0,16.02,211.1,94.0,9.50,7.8,8,2.11,1.0,False
3318,OK,52,415,No,No,0,124.9,131.0,21.23,300.5,118.0,25.54,192.5,106.0,8.66,11.6,4,3.13,2.0,False
3319,WY,89,415,No,No,0,115.4,99.0,19.62,209.9,115.0,17.84,280.9,112.0,12.64,15.9,6,4.29,3.0,False
3320,GA,122,510,Yes,No,0,140.0,101.0,23.80,196.4,77.0,16.69,120.1,133.0,5.40,9.7,4,2.62,4.0,True
3321,VT,60,415,No,No,0,193.9,118.0,32.96,85.0,110.0,7.23,210.1,134.0,9.45,13.2,8,3.56,3.0,False
3322,MD,62,408,No,No,0,321.1,105.0,54.59,265.5,122.0,22.57,180.5,72.0,8.12,11.5,2,3.11,4.0,True
3323,IN,117,415,No,No,0,118.4,126.0,20.13,249.3,97.0,21.19,227.0,56.0,10.22,13.6,3,3.67,5.0,True
3324,WV,159,415,No,No,0,169.8,114.0,28.87,197.7,105.0,16.80,193.7,82.0,8.72,11.6,4,3.13,1.0,False
3325,OH,78,408,No,No,0,193.4,99.0,32.88,116.9,88.0,9.94,243.3,109.0,10.95,9.3,4,2.51,2.0,False
3326,OH,96,415,No,No,0,106.6,128.0,18.12,284.8,87.0,24.21,178.9,92.0,8.05,14.9,7,4.02,1.0,False
3327,SC,79,415,No,No,0,134.7,98.0,22.90,189.7,68.0,16.12,221.4,128.0,9.96,11.8,5,3.19,2.0,False
3328,AZ,192,415,No,Yes,36,156.2,77.0,26.55,215.5,126.0,18.32,279.1,83.0,12.56,9.9,6,2.67,2.0,False
3329,WV,68,415,No,No,0,231.1,57.0,39.29,153.4,55.0,13.04,191.3,123.0,8.61,9.6,4,2.59,3.0,False
3330,RI,28,510,No,No,0,180.8,109.0,30.74,288.8,58.0,24.55,191.9,91.0,8.64,14.1,6,3.81,2.0,False
3331,CT,184,510,Yes,No,0,213.8,105.0,36.35,159.6,84.0,13.57,139.2,137.0,6.26,5.0,10,1.35,2.0,False
3332,TN,74,415,No,Yes,25,234.4,113.0,39.85,265.9,82.0,22.60,241.4,77.0,10.86,13.7,4,3.70,0.0,False

## Create a DataFrame from dictionary

In [13]:
tempDic = {'Name':['hosne','mubarak','tasmir'],'Designation':['S/W Eng', 'Video editor', 'Doctor'], 'Salary':[100,200,300]}

In [14]:
dicDf = pd.DataFrame.from_dict(tempDic)

In [15]:
dicDf

      Name   Designation  Salary
0    hosne       S/W Eng     100
1  mubarak  Video editor     200
2   tasmir        Doctor     300

In [17]:
df.columns

Index(['State', 'Account length', 'Area code', 'International plan',
       'Voice mail plan', 'Number vmail messages', 'Total day minutes',
       'Total day calls', 'Total day charge', 'Total eve minutes',
       'Total eve calls', 'Total eve charge', 'Total night minutes',
       'Total night calls', 'Total night charge', 'Total intl minutes',
       'Total intl calls', 'Total intl charge', 'Customer service calls',
       'Churn'],
      dtype='object')

In [18]:
df.dtypes

State                      object
Account length              int64
Area code                   int64
International plan         object
Voice mail plan            object
Number vmail messages       int64
Total day minutes         float64
Total day calls           float64
Total day charge          float64
Total eve minutes         float64
Total eve calls           float64
Total eve charge          float64
Total night minutes       float64
Total night calls         float64
Total night charge        float64
Total intl minutes        float64
Total intl calls            int64
Total intl charge         float64
Customer service calls    float64
Churn                      object
dtype: object

In [19]:
df.State

0       KS
1       OH
2       NJ
3       OH
4       OK
        ..
3328    AZ
3329    WV
3330    RI
3331    CT
3332    TN
Name: State, Length: 3333, dtype: object

In [21]:
df['International plan']

0        No
1        No
2        No
3       Yes
4       Yes
       ...
3328     No
3329     No
3330     No
3331    Yes
3332     No
Name: International plan, Length: 3333, dtype: object

In [22]:
df[['State','Number vmail messages']]

     State  Number vmail messages
0       KS                     25
1       OH                     26
2       NJ                      0
3       OH                      0
4       OK                      0
...    ...                    ...
3328    AZ                     36
3329    WV                      0
3330    RI                      0
3331    CT                      0
3332    TN                     25

[3333 rows x 2 columns]

In [23]:
df.head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False

In [24]:
df.State.unique()

array(['KS', 'OH', 'NJ', 'OK', 'AL', 'MA', 'MO', 'LA', 'WV', 'IN', 'RI',
       'IA', 'MT', 'NY', 'ID', 'VT', 'VA', 'TX', 'FL', 'CO', 'AZ', 'SC',
       'NE', 'WY', 'HI', 'IL', 'NH', 'GA', 'AK', 'MD', 'AR', 'WI', 'OR',
       'MI', 'DE', 'UT', 'CA', 'MN', 'SD', 'NC', 'WA', 'NM', 'NV', 'DC',
       'KY', 'ME', 'MS', 'TN', 'PA', 'CT', 'ND'], dtype=object)

In [27]:
df[df['International plan']=='Yes']

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False
5,AL,118,510,Yes,No,0,223.4,98.0,37.98,220.6,101.0,18.75,203.9,118.0,9.18,6.3,6,1.70,0.0,False
7,MO,147,415,Yes,No,0,157.0,79.0,26.69,103.1,94.0,8.76,211.8,96.0,9.53,7.1,6,1.92,0.0,False
9,WV,141,415,Yes,Yes,37,258.6,84.0,43.96,222.0,111.0,18.87,326.4,97.0,14.69,11.2,5,3.02,0.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3304,IL,71,510,Yes,No,0,186.1,114.0,31.64,198.6,140.0,16.88,206.5,80.0,9.29,13.8,5,3.73,4.0,True
3309,VT,100,408,Yes,No,0,219.4,112.0,37.30,225.7,102.0,19.18,255.3,95.0,11.49,12.0,4,3.24,4.0,False
3317,SD,163,415,Yes,No,0,197.2,90.0,33.52,188.5,113.0,16.02,211.1,94.0,9.50,7.8,8,2.11,1.0,False
3320,GA,122,510,Yes,No,0,140.0,101.0,23.80,196.4,77.0,16.69,120.1,133.0,5.40,9.7,4,2.62,4.0,True
3331,CT,184,510,Yes,No,0,213.8,105.0,36.35,159.6,84.0,13.57,139.2,137.0,6.26,5.0,10,1.35,2.0,False

In [29]:
df[(df['International plan']=='Yes') & (df['Churn']==True)]

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
41,MD,135,408,Yes,Yes,41,173.1,85.0,29.43,203.9,107.0,17.33,122.2,78.0,5.50,14.6,15,3.94,0.0,True
115,ME,36,510,Yes,Yes,42,196.8,89.0,33.46,254.9,122.0,21.67,138.3,126.0,6.22,20.0,6,5.40,0.0,True
144,VT,117,408,Yes,No,0,167.1,86.0,28.41,177.5,87.0,15.09,249.4,132.0,11.22,14.1,7,3.81,2.0,True
198,ME,131,510,Yes,Yes,26,292.9,101.0,49.79,199.7,97.0,16.97,255.3,127.0,11.49,13.8,7,3.73,4.0,True
214,FL,70,510,Yes,No,0,226.7,98.0,38.54,228.1,115.0,19.39,73.2,93.0,3.29,17.6,4,4.75,2.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3246,NC,77,408,Yes,Yes,44,103.2,117.0,17.54,236.3,86.0,20.09,203.5,101.0,9.16,11.9,2,3.21,0.0,True
3255,RI,138,510,Yes,No,0,286.2,61.0,48.65,187.2,60.0,15.91,146.2,114.0,6.58,11.0,4,2.97,2.0,True
3291,MI,119,510,Yes,Yes,22,172.1,119.0,29.26,223.6,133.0,19.01,150.0,94.0,6.75,13.9,20,3.75,1.0,True
3304,IL,71,510,Yes,No,0,186.1,114.0,31.64,198.6,140.0,16.88,206.5,80.0,9.29,13.8,5,3.73,4.0,True
3320,GA,122,510,Yes,No,0,140.0,101.0,23.80,196.4,77.0,16.69,120.1,133.0,5.40,9.7,4,2.62,4.0,True

In [31]:
df.head(20)

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False
5,AL,118,510,Yes,No,0,223.4,98.0,37.98,220.6,101.0,18.75,203.9,118.0,9.18,6.3,6,1.70,0.0,False
6,MA,121,510,No,Yes,24,218.2,88.0,37.09,348.5,108.0,29.62,212.6,118.0,9.57,7.5,7,2.03,3.0,NaN
7,MO,147,415,Yes,No,0,157.0,79.0,26.69,103.1,94.0,8.76,211.8,96.0,9.53,7.1,6,1.92,0.0,False
8,LA,117,408,No,No,0,184.5,97.0,31.37,351.6,80.0,29.89,215.8,90.0,9.71,8.7,4,2.35,1.0,False
9,WV,141,415,Yes,Yes,37,258.6,84.0,43.96,222.0,111.0,18.87,326.4,97.0,14.69,11.2,5,3.02,0.0,False
10,IN,65,415,No,No,0,129.1,137.0,21.95,228.5,83.0,19.42,208.8,111.0,9.40,12.7,6,3.43,4.0,True
11,RI,74,415,No,No,0,187.7,127.0,31.91,163.4,148.0,13.89,196.0,94.0,8.82,9.1,5,2.46,0.0,False
12,IA,168,408,No,No,0,NaN,NaN,NaN,104.9,71.0,8.92,141.1,128.0,6.35,11.2,2,3.02,1.0,False
13,MT,95,510,No,No,0,NaN,NaN,NaN,247.6,75.0,21.05,192.3,115.0,8.65,12.3,5,3.32,3.0,False
14,IA,62,415,No,No,0,NaN,NaN,NaN,307.2,76.0,26.11,203.0,99.0,9.14,13.1,6,3.54,4.0,False
15,NY,161,415,No,No,0,NaN,NaN,NaN,317.8,97.0,27.01,160.6,128.0,7.23,5.4,9,1.46,4.0,True
16,ID,85,408,No,Yes,27,NaN,NaN,NaN,280.9,90.0,23.88,89.3,NaN,4.02,13.8,4,3.73,1.0,False
17,VT,93,510,No,No,0,NaN,NaN,NaN,218.2,111.0,18.55,129.6,121.0,5.83,8.1,3,2.19,3.0,False
18,VA,76,510,No,Yes,33,NaN,NaN,NaN,212.8,65.0,18.09,165.7,108.0,7.46,10.0,5,2.70,1.0,False
19,TX,73,415,No,No,0,NaN,NaN,NaN,NaN,88.0,13.56,192.8,74.0,8.68,13.0,2,3.51,1.0,False

In [30]:
df.iloc[14]

State                        IA
Account length               62
Area code                   415
International plan           No
Voice mail plan              No
Number vmail messages         0
Total day minutes           NaN
Total day calls             NaN
Total day charge            NaN
Total eve minutes         307.2
Total eve calls            76.0
Total eve charge          26.11
Total night minutes       203.0
Total night calls          99.0
Total night charge         9.14
Total intl minutes         13.1
Total intl calls              6
Total intl charge          3.54
Customer service calls      4.0
Churn                     False
Name: 14, dtype: object

In [32]:
df.iloc[14, 1]

np.int64(62)

In [40]:
df.iloc[14, -1]

False

#Slicing

In [41]:
df.iloc[9:20]

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
9,WV,141,415,Yes,Yes,37,258.6,84.0,43.96,222.0,111.0,18.87,326.4,97.0,14.69,11.2,5,3.02,0.0,False
10,IN,65,415,No,No,0,129.1,137.0,21.95,228.5,83.0,19.42,208.8,111.0,9.40,12.7,6,3.43,4.0,True
11,RI,74,415,No,No,0,187.7,127.0,31.91,163.4,148.0,13.89,196.0,94.0,8.82,9.1,5,2.46,0.0,False
12,IA,168,408,No,No,0,NaN,NaN,NaN,104.9,71.0,8.92,141.1,128.0,6.35,11.2,2,3.02,1.0,False
13,MT,95,510,No,No,0,NaN,NaN,NaN,247.6,75.0,21.05,192.3,115.0,8.65,12.3,5,3.32,3.0,False
14,IA,62,415,No,No,0,NaN,NaN,NaN,307.2,76.0,26.11,203.0,99.0,9.14,13.1,6,3.54,4.0,False
15,NY,161,415,No,No,0,NaN,NaN,NaN,317.8,97.0,27.01,160.6,128.0,7.23,5.4,9,1.46,4.0,True
16,ID,85,408,No,Yes,27,NaN,NaN,NaN,280.9,90.0,23.88,89.3,NaN,4.02,13.8,4,3.73,1.0,False
17,VT,93,510,No,No,0,NaN,NaN,NaN,218.2,111.0,18.55,129.6,121.0,5.83,8.1,3,2.19,3.0,False
18,VA,76,510,No,Yes,33,NaN,NaN,NaN,212.8,65.0,18.09,165.7,108.0,7.46,10.0,5,2.70,1.0,False
19,TX,73,415,No,No,0,NaN,NaN,NaN,NaN,88.0,13.56,192.8,74.0,8.68,13.0,2,3.51,1.0,False

In [43]:
state = df.copy()

In [44]:
state.set_index('State', inplace=True)

In [45]:
state.head()

,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
State,,,,,,,,,,,,,,,,,,,
KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False
OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False
NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False
OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False
OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False

In [47]:
state.loc['KS']

,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
State,,,,,,,,,,,,,,,,,,,
KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False
KS,70,408,No,No,0,232.1,122.0,39.46,292.3,112.0,24.85,201.2,112.0,9.05,0.0,0,0.00,3.0,False
KS,92,408,Yes,No,0,62.6,111.0,10.64,180.6,126.0,15.35,221.7,80.0,9.98,10.4,2,2.81,1.0,True
KS,137,408,No,No,0,205.9,88.0,35.00,209.3,86.0,17.79,289.9,84.0,13.05,14.5,4,3.92,2.0,False
KS,132,415,No,No,0,83.4,110.0,14.18,232.2,137.0,19.74,146.7,114.0,6.60,7.6,5,2.05,1.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
KS,164,510,No,Yes,30,238.8,100.0,40.60,230.0,121.0,19.55,206.3,66.0,9.28,13.2,8,3.56,1.0,False
KS,101,415,No,No,0,231.3,87.0,39.32,224.7,88.0,19.10,214.6,69.0,9.66,7.2,7,1.94,1.0,False
KS,127,415,No,Yes,24,154.8,69.0,26.32,177.2,105.0,15.06,207.6,102.0,9.34,9.0,4,2.43,1.0,False
KS,57,415,No,No,0,158.1,117.0,26.88,115.2,149.0,9.79,182.4,92.0,8.21,11.8,7,3.19,0.0,False
KS,170,415,No,Yes,42,199.5,119.0,33.92,135.0,90.0,11.48,184.6,49.0,8.31,10.9,3,2.94,4.0,True

In [48]:
state.reset_index()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,AZ,192,415,No,Yes,36,156.2,77.0,26.55,215.5,126.0,18.32,279.1,83.0,12.56,9.9,6,2.67,2.0,False
3329,WV,68,415,No,No,0,231.1,57.0,39.29,153.4,55.0,13.04,191.3,123.0,8.61,9.6,4,2.59,3.0,False
3330,RI,28,510,No,No,0,180.8,109.0,30.74,288.8,58.0,24.55,191.9,91.0,8.64,14.1,6,3.81,2.0,False
3331,CT,184,510,Yes,No,0,213.8,105.0,36.35,159.6,84.0,13.57,139.2,137.0,6.26,5.0,10,1.35,2.0,False
3332,TN,74,415,No,Yes,25,234.4,113.0,39.85,265.9,82.0,22.60,241.4,77.0,10.86,13.7,4,3.70,0.0,False

In [49]:
df.isnull().sum()

State                      0
Account length             0
Area code                  0
International plan         0
Voice mail plan            0
Number vmail messages      0
Total day minutes         10
Total day calls           10
Total day charge          18
Total eve minutes          9
Total eve calls            8
Total eve charge           0
Total night minutes        0
Total night calls          1
Total night charge         0
Total intl minutes         0
Total intl calls           0
Total intl charge          5
Customer service calls     5
Churn                      8
dtype: int64

In [51]:
df.dropna(inplace=True)

In [52]:
df.isnull().sum()

State                     0
Account length            0
Area code                 0
International plan        0
Voice mail plan           0
Number vmail messages     0
Total day minutes         0
Total day calls           0
Total day charge          0
Total eve minutes         0
Total eve calls           0
Total eve charge          0
Total night minutes       0
Total night calls         0
Total night charge        0
Total intl minutes        0
Total intl calls          0
Total intl charge         0
Customer service calls    0
Churn                     0
dtype: int64

In [53]:
df

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,AZ,192,415,No,Yes,36,156.2,77.0,26.55,215.5,126.0,18.32,279.1,83.0,12.56,9.9,6,2.67,2.0,False
3329,WV,68,415,No,No,0,231.1,57.0,39.29,153.4,55.0,13.04,191.3,123.0,8.61,9.6,4,2.59,3.0,False
3330,RI,28,510,No,No,0,180.8,109.0,30.74,288.8,58.0,24.55,191.9,91.0,8.64,14.1,6,3.81,2.0,False
3331,CT,184,510,Yes,No,0,213.8,105.0,36.35,159.6,84.0,13.57,139.2,137.0,6.26,5.0,10,1.35,2.0,False
3332,TN,74,415,No,Yes,25,234.4,113.0,39.85,265.9,82.0,22.60,241.4,77.0,10.86,13.7,4,3.70,0.0,False

In [54]:
df.drop('Total night minutes', axis=1)

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,91.0,11.01,10.0,3,2.70,1.0,False
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,103.0,11.45,13.7,3,3.70,1.0,False
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,104.0,7.32,12.2,5,3.29,0.0,False
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,89.0,8.86,6.6,7,1.78,2.0,False
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,121.0,8.41,10.1,3,2.73,3.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,AZ,192,415,No,Yes,36,156.2,77.0,26.55,215.5,126.0,18.32,83.0,12.56,9.9,6,2.67,2.0,False
3329,WV,68,415,No,No,0,231.1,57.0,39.29,153.4,55.0,13.04,123.0,8.61,9.6,4,2.59,3.0,False
3330,RI,28,510,No,No,0,180.8,109.0,30.74,288.8,58.0,24.55,91.0,8.64,14.1,6,3.81,2.0,False
3331,CT,184,510,Yes,No,0,213.8,105.0,36.35,159.6,84.0,13.57,137.0,6.26,5.0,10,1.35,2.0,False
3332,TN,74,415,No,Yes,25,234.4,113.0,39.85,265.9,82.0,22.60,77.0,10.86,13.7,4,3.70,0.0,False

In [55]:
df['New coulmn'] = df['Total day charge'] + df['Total night charge']

In [56]:
df

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,...,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn,New coulmn
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,...,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False,56.08
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,...,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False,38.92
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,...,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False,48.70
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,...,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False,59.76
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,...,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False,36.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,AZ,192,415,No,Yes,36,156.2,77.0,26.55,215.5,...,18.32,279.1,83.0,12.56,9.9,6,2.67,2.0,False,39.11
3329,WV,68,415,No,No,0,231.1,57.0,39.29,153.4,...,13.04,191.3,123.0,8.61,9.6,4,2.59,3.0,False,47.90
3330,RI,28,510,No,No,0,180.8,109.0,30.74,288.8,...,24.55,191.9,91.0,8.64,14.1,6,3.81,2.0,False,39.38
3331,CT,184,510,Yes,No,0,213.8,105.0,36.35,159.6,...,13.57,139.2,137.0,6.26,5.0,10,1.35,2.0,False,42.61
3332,TN,74,415,No,Yes,25,234.4,113.0,39.85,265.9,...,22.60,241.4,77.0,10.86,13.7,4,3.70,0.0,False,50.71

In [57]:
df.iloc[0,-1]=60

In [58]:
df

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,...,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn,New coulmn
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,...,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False,60.00
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,...,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False,38.92
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,...,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False,48.70
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,...,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False,59.76
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,...,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False,36.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,AZ,192,415,No,Yes,36,156.2,77.0,26.55,215.5,...,18.32,279.1,83.0,12.56,9.9,6,2.67,2.0,False,39.11
3329,WV,68,415,No,No,0,231.1,57.0,39.29,153.4,...,13.04,191.3,123.0,8.61,9.6,4,2.59,3.0,False,47.90
3330,RI,28,510,No,No,0,180.8,109.0,30.74,288.8,...,24.55,191.9,91.0,8.64,14.1,6,3.81,2.0,False,39.38
3331,CT,184,510,Yes,No,0,213.8,105.0,36.35,159.6,...,13.57,139.2,137.0,6.26,5.0,10,1.35,2.0,False,42.61
3332,TN,74,415,No,Yes,25,234.4,113.0,39.85,265.9,...,22.60,241.4,77.0,10.86,13.7,4,3.70,0.0,False,50.71

In [59]:
df.to_csv('output.csv')

In [60]:
df.to_json('output.json')

In [62]:
df.to_html()df

SyntaxError: invalid syntax (1601430706.py, line 1)

In [63]:
del df

In [64]:
df

NameError: name 'df' is not defined